apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ecommerce-app
spec:
  type: NodePort # Expose externally via NodePort for Minikube
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80 # Port service listens on
      targetPort: 80 # Port the Nginx container listens on
      nodePort: 30080 # Optional: Specify NodePort (adjust for Minikube)
