apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: ecommerce-app
data:
  BACKEND_API_URL: "http://backend-api-service.ecommerce-app.svc.cluster.local:3001" # Reference backend API service

