apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  DB_HOST: "postgres-service"   # Kubernetes Service name for PostgreSQL
  DB_NAME: "ecommerce_db"       # Database name
  DB_PORT: "5432"               # Default PostgreSQL port
