apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
data:
  user: bnViZQ== # Base64 encoded nube
  password: bnViZQ== # Base64 encoded nube
  rootpassword: bnViZQ== # Base64 encoded nube