apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  DB_USER: "cG9zdGdyZXM="   # Base64 encoded value of "postgres"
  DB_PASSWORD: "c2VjdXJlX3Bhc3N3b3Jk"  # Base64 encoded password (replace with actual base64 value)
