apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce-app
type: Opaque
data:
  DB_USER: dXNlcg== # Base64 for 'user'
  DB_PASSWORD: cGFzc3dvcmQ= # e.g., cGFzc3dvcmQ= for 'password'
