# ClusterIP Service for Backend API access
apiVersion: v1
kind: Service
metadata:
  name: postgres-db-service
  namespace: ecommerce-app
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432