apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: ecommerce-app
spec:
  serviceName: postgres-db-headless
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_NAME  # Use existing ConfigMap key
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: DB_PORT
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            exec:
              command:
                [
                  "pg_isready",
                  "-U",
                  "$(POSTGRES_USER)",
                  "-d",
                  "$(POSTGRES_DB)",
                  "-h",
                  "$(DB_HOST)",
                  "-p",
                  "$(DB_PORT)"
                ]
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                [
                  "pg_isready",
                  "-U",
                  "$(POSTGRES_USER)",
                  "-d",
                  "$(POSTGRES_DB)",
                  "-h",
                  "$(DB_HOST)",
                  "-p",
                  "$(DB_PORT)"
                ]
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: standard 
